logging:
  config: classpath:logback.xml
server:
#  port: 8083
  port: 8084
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://localhost:8082
    executor:
      appname: kettle-job
      ip: ''
#      logpath: /Users/selegant/Downloads/tmp/data/applogs/xxl-job/jobhandler
      logpath: C:/Users/薛云腾/Desktop/log
      logretentiondays: 30
#      port: 9997
      port: 9998
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://selegant.synology.me:33306/etl?Unicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://node1:3306/etl?Unicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
#    password: root
    tomcat:
      max-active: 30
      max-wait: 10000
      test-on-borrow: true
      validation-interval: 30000
      validation-query: SELECT 1
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

kettle:
  plugins-path: /Users/selegant/Downloads/plugins #KETTLE插件地址
  app-name: kettle-job #执行器名称
  waterfall-statics: true
