server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etl?Unicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    tomcat:
      max-active: 30
      max-wait: 10000
      test-on-borrow: true
      validation-interval: 30000
      validation-query: SELECT 1
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    password: xxx
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: xxx@qq.com

xxl:
  job:
    accessToken: ''
    i18n: ''
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

mapper:
  i-d-e-n-t-i-t-y: MYSQL
  mappers: com.baomidou.mybatisplus.core.mapper.BaseMapper
  not-empty: true
  enum-as-simple-type: true

kettle:
  plugins-path: /Users/selegant/Downloads/plugins #KETTLE插件地址
  app-name: kettle-job #执行器名称
